container/cli.py, container/engine.py
Subcommand option parsing is not working, so this is a temporary hack to at least have subcommands work.
=> Temporary fixes

README.md
Just something to get folks started. :)
=> Basic install instructions

docs/rst/index.rst
this file looks great. just nit-picking contractions and a bit of punctuation.
=> Minor editing

container/templates/ansible-dockerfile.j2
ssh keeps timing out. Might be because I don't have my private key installed.
=> Switch from ssh to https.

container/docker/engine.py
Reverts ansible/ansible-container#38
=> Revert "Enable setting docker API version from environment."

docs/rst/installation.rst
Nit-picky changes -- removing contractions, avoiding future-tense, adding comma
=> Update Installation.rst (minor)

container/docker/engine.py, container/engine.py, container/exceptions.py, container/templates/galaxy-docker-compose.j2.yml, requirements.txt
- Run galaxy in the ansible build container
- ansible is not a requirement
- If username/password is passed and authentication to the registry is successful, update ~/.docker/config.json.
=> Fix galaxy role init. Remove ansible from requirement. Update docker config on login.

example/ansible/container.yml
Reverts ansible/ansible-container#56
=> Stupid me! Access the example site on port 80.

container/templates/ansible/container.j2.yml
paths were wrong for dumb-init and apache-ctl in the example in the template
=> Fix example so it works

INSTALL.md
The current link goes to a 404 page.
=> Update link to Docker toolkit.

docs/rst/installation.rst, requirements.txt
Removed unnecessary dependencies from requirements.txt and updated the install.
=> Fix requirements

container/cli.py, container/docker/engine.py, container/engine.py, container/shipit/openshift/deployment.py, docs/rst/deploy_kubernetes.rst, docs/rst/reference/push.rst, docs/rst/registry_auth.rst
- Fix #92 - combine --namespace, --url and --push-to
- Fix a parsing error in OpenShift Deployment module.
=> On push cmd eliminate --url and --namespace.

.gitignore, container/config.py, container/engine.py, container/templates/shipit_role/README.j2, container/templates/shipit_role/defaults.j2.yml, container/templates/shipit_role/meta.j2.yml, container/templates/shipit_role/test.j2.yml, container/templates/shipit_role/travis.j2.yml
- Fixes issue #114 shipit templates not found. 
- Adds to commits intended to improve error handling.
=> Fix missing shipit templates

AUTHORS, INSTALL.md, container/cli.py, container/docker/engine.py, container/engine.py, docs/rst/example.rst, docs/rst/installation.rst, setup.py
- New Module Pull Request
```
```
=> Release prep

docs/rst/deploy_kubernetes.rst
=> authrorize

docs/rst/registry_auth.rst
Docs Pull Request
Typo in --username .
=> Typo in --username

AUTHORS, container/docker/engine.py
=> Preserve user/workdir/cmd from compose - fixes #116

AUTHORS
- Adding Shubham Minglani to list of authors.
- Changed my email.
=> Added Shubham Minglani to authors.

README.md
On README add list of ways to get involved with the project. Includes the basics:
- #ansible-container on irc.freenode.net
- for code submissions, review the contributor guidelines
- join the mailing list
- open an issue.
=> Update readme with ways to get involved.

CONTRIBUTORS.md
Update contributor guidelines with branching strategy info.
=> Update contribution words.

AUTHORS, container/docker/engine.py
If a base image has an entrypoint specified, it can't currently be built upon or listed. This fixes that.
Using pulp/qpid:latest, before:
```
(qpid)Big-Kahuna:qpid jginsberg$ ansible-container build
Starting Docker Compose engine to build your images...
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
No image found for tag qpid-qpid1:latest, so building from scratch
No image found for tag qpid-qpid3:latest, so building from scratch
No image found for tag qpid-qpid2:latest, so building from scratch
Attaching to ansible_ansible-container_1, ansible_qpid1_1, ansible_qpid3_1, ansible_qpid2_1
qpid1_1              | 2016-08-18 16:48:56 [Unspecified] debug Config file not read: /etc/qpid/qpidd.conf
qpid1_1              | 2016-08-18 16:48:56 …
```
=> Disable entrypoint on build/list operations.

container/shipit/base_engine.py
=> Typo in base_engine.py

container/__init__.py
Increments version to 0.2.0-pre. Should have done this as soon as 0.1.0 went out. Assuming we want to do another *beta* release (or whatever we're calling it) and not a 1.0.0 release.
=> Increment version to 0.2.0

container/templates/build-docker-compose.j2.yml, container/templates/listhosts-docker-compose.j2.yml
This should address #192 and #193
=> Fix some issues with socket mounting

docs/rst/roadmaps/roadmap_0_2_0.rst
Fixes minor typos, style issues and grammatical errors on 0.2.0 roadmap doc.
=> 0.2.0 roadmap edits

container/docker/engine.py
Fixes issue #177 by properly parsing the docker push output when multiple json lines from the data stream are returned
=> Properly parse docker push output stream

docs/rst/container_yml/index.rst, docs/rst/container_yml/reference.rst, docs/rst/container_yml/template.rst, docs/rst/index.rst, docs/rst/reference/build.rst, update-authors.py
Docs Pull Request
Add missing docs for Jinja templating in container.yml.
=> Add container.yml docs:

container/config.py, container/exceptions.py, container/filters/__init__.py, container/filters/general.py, container/filters/lookup/__init__.py, container/filters/lookup/version.py, container/shipit/kubernetes/service.py, container/temp.py, container/utils.py, docs/rst/container_yml/template.rst, test/unit/container/test_config.py
More robust templating in container.yml
- Imports Ansible lookups, if Ansible is available
- Imports Ansible filters, if Ansible is available
- Adds support for custom lookups
- Adds support for custom filters
- Adds doc updates 
- defaults can now includes Jinja expressions
- variable files now include Jinja expressions
=> Make Ansible Jinja lookups and filters available to Ansible Container

docs/rst/reference/run.rst, docs/rst/reference/shipit/kube.rst, docs/rst/reference/shipit/openshift.rst
Minor clean up in `run` and `shipit` reference docs.
=> Doc updates

container/docker/engine.py, container/templates/ansible-dockerfile.j2, container/templates/docker.repo, test/docker-compose.yml, test/run.sh
1.10.3 of docker was being installed in the build container, and it was ignoring the DOCKER_CERT_PATH environment variable.
=> Use docker > 1.10.3 && < 1.12

container/docker/engine.py, test/local/ansible/container.yml
=> tests: handle docker client/server version mismatches

container/cli.py, container/config.py, container/docker/engine.py, container/engine.py, container/exceptions.py, docs/rst/reference/build.rst
Adds `service` option to the `build` command. This makes it possible to circumvent the orchestrated build and only build a subset of services.
=> Allow building a subset of services.

AUTHORS, container/engine.py, container/templates/ansible/meta.j2.yml, docs/rst/getting_started.rst, docs/rst/reference/init.rst
Adds meta.yml to files created by `init`.
=> Add meta.yml

container/engine.py
- New Module Pull Request
```
```
=> Handle missing YAML value gracefully - fixes #265

container/templates/ac_galaxy.py
=> It's version not vesion.

test/integration/projects/requirements/ansible/requirements.yml
Integration tests depended on github.com/chouseknecht/ansible-role-apache, which got deleted. Switched the dependency to github.com/geerlingguy/ansible-role-apache, which I think is likely to never be deleted.
=> Deleted the role. Oops!

AUTHORS, proposals/compose-v2.md
- Proposal
Adds a proposal for:
- Support for Docker Compose v2
- Specification for `container.yml`
- Guidelines for maintaining `container.yml`
=> WIP - proposed Compose V2 support

.mailmap, AUTHORS, tox.ini
Another commit with an update of `.mailmap` and `AUTHORS` files.
=> CI: execute the test suite using Python 3.4 and Python 3.5

ROADMAP.rst, docs/rst/roadmaps/index.rst, docs/rst/roadmaps/roadmap_0_3_0.rst
Fixes #305 by providing a 0.3.0 roadmap
=> Updated Roadmap for 0.3.0 and fix #305

container/templates/ansible-dockerfile.j2, docs/rst/configure_openshift.rst
Install Ansible in the build container using the editable (-e) option.
=> Fix broken tests

AUTHORS, README.md, docs/rst/configure_openshift.rst, docs/rst/container_yml/reference.rst, docs/rst/roadmaps/roadmap_0_3_0.rst
- Updates demo requirements on README
- Sets expected release date to mid January
- Installs Ansible in the build container using -e
=> Doc fixes and minor cleanup

AUTHORS, docs/rst/configure_openshift.rst, docs/rst/getting_started.rst
- Link to the new demo site 
- Link to ansible/django-gulp-nginx
=> Link to the demo project

container/templates/ansible-dockerfile.j2, container/templates/ansible/requirements.j2.txt, requirements.txt, test/build-test-img/ansible/main.yml, test/build-test-img/ansible/requirements.txt, test/integration/projects/environment/ansible/container.yml, test/integration/projects/environment/ansible/main.yml, test/integration/projects/environment/ansible/requirements.txt, test/integration/projects/minimal/ansible/requirements.txt, test/integration/projects/minimal_sleep/ansible/requirements.txt, test/integration/projects/requirements/ansible/requirements.txt, test/integration/projects/vartest/ansible/requirements.txt, test/integration/test_slow.py, test/local/ansible/container.yml, test/local/ansible/requirements.txt
Adds support for Docker 1.12, including docker-compose 1.9.0 and docker-py 1.10.6, and resolves #314.
We can't merge this until [docker/compose#4090](https://github.com/docker/compose/issues/4090) gets resolved.
=> WIP: Upgrade to Docker 1.12

ROADMAP.rst
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ansible/ansible-container/346)
=> Red Hat (not RedHat)

container/shipit/kubernetes/service.py, container/shipit/openshift/service.py
=> Change type to request_type

README.md
The Travis CI badge should reflect the state of the develop branch.
=> Point Travis badge to develop branch

docs/rst/container_yml/reference.rst
Fixes 2 small typos in container_yml reference
=> Docs typo fix for container_yml/reference

docs/rst/openshift/index.rst
Correct Openshift to OpenShift
=> Correct casing of OpenShift

docs/rst/openshift/adb.rst
Fix small issues with the doc: markup and ansible-galaxy install instruction
=> Fix small issue with install instruction

docs/rst/openshift/minishift.rst
Fixed a small issue of a missing character
=> Fix ansible-galaxy install instruction

AUTHORS, docs/rst/container_yml/template.rst
A bit of clean-up, and a note or two for clarity.
=> Adds clean-up and notes to Ansible Vault docs

container/docker/engine.py
Minor typo in error message I came across while breaking things.
=> Minor typo fix

AUTHORS, container/shipit/openshift/deployment.py, container/shipit/openshift/modules/oso_deployment.py, container/shipit/openshift/modules/oso_service.py, container/shipit/openshift/service.py
=> Adds support for port protocol in OpenShift deployments

requirements.txt
Adds `ruamel.yaml` to `requirements.txt`.
=> Adds ruamel.yaml

container/cli.py, container/config.py, container/docker/engine.py, container/docker/importer.py, container/utils/__init__.py, container/utils/logmux.py, container/utils/visibility.py, requirements.txt, test/tests/validate_build.py, test/tests/validate_import.py
This pull request allows to run the test suite using Python 3.5.
=> Python 3 compatibility

conductor-requirements.txt, container/cli.py, container/core.py, container/docker/engine.py, container/docker/templates/conductor-dockerfile.j2, container/exceptions.py, container/k8s/base_deploy.py, container/k8s/base_engine.py, container/k8s/engine.py, container/openshift/deploy.py, container/openshift/engine.py
- Adds support for OpenShift routes
- Minor cleanup of error handling. 
- Removes copy of ansible/module_utils source files into conductor
=> Continued work on `k8s` and `openshift`

container/config.py, container/core.py, container/k8s/base_deploy.py, container/k8s/base_engine.py, container/utils/__init__.py
=> Making k8s/openshift volumes work

container/core.py, container/docker/engine.py, container/engine.py, container/k8s/base_engine.py
=> Fixes version

container/core.py, container/docker/engine.py
To having the full run/stop/restart/destroy cycle in a single playbook
that's distinguished based on tags. This also adds a `run_playbook`
option for lists of Ansible tags
Implements #377 for docker runner
```
- gather_facts: false
tasks:
- docker_service:
definition:
services: &id001
web:
image: house-test-ac-web:latest
working_dir: /
entrypoint:
- /usr/bin/entrypoint.sh
user: apache
command:
- /usr/bin/dumb-init
- httpd
- -DFOREGROUND
ports:
- 8000:8080
- 4443:8443
version: '2'
state: present
project_name: house-test-ac
tags:
- start
- docker_service:
definition:
services: *id001
version: '2'
state: present
project_name: house-test-ac
restarted: true
tags:
- restart
- docker_service:
definition:
services: *id001
version: '2'
state: present
project_name: …
```
=> Convert from playbook per function (one for run, stop, etc)

container/config.py, container/core.py, container/engine.py, container/k8s/base_deploy.py, container/k8s/base_engine.py, container/k8s/deploy.py, container/openshift/deploy.py, container/openshift/engine.py
Rebases existing branch, and modifies k8s/openshift engine to generate a full lifecycle playbook.
=> Playbook lifecycle

container/docker/engine.py, container/k8s/base_deploy.py
=> Include volumes in Docker playbook generation

docs/rst/getting_started.rst
Single word change to the Getting Started section. Change should be the author's original intention.
=> Minor grammar change to Getting Started

AUTHORS, container/utils/__init__.py
=> Anticipate missing meta file

container/core.py, container/docker/engine.py, test/tests/validate_build.py
=> Run build with --privilege

container/docker/engine.py
=> Adds missing --roles-path support

container/config.py, test/roles/validate-config/files/container.yml, test/roles/validate-config/files/test-variables/tasks/main.yml, test/roles/validate-config/tasks/main.yml, test/tests/validate_config.py
- Adding tests
Adding tests in response to #418 (Properly handle config variable inheritance)
=> Test that extra vars are passed to ansible-playbook

setup.py
=> Update setup.py with openshift release

container/docker/importer.py
=> Support "key value" LABEL format

AUTHORS, container/docker/engine.py
Fixing a regression caused by #479 
Fixes issue #484
=> During build, remove 'links'

docs/rst/container_yml/reference.rst
trivial YAML syntax fix for the doc :)
=> fix YAML syntax in the registries section of the container.yml doc

container/core.py
Signed-off-by: Aaron Cowdin <aaron.cowdin@gmail.com>
Example Fix for #499
=> Example fix for Issue #499

AUTHORS, container/docker/importer.py
- Removes outer quotes on label values via shlex.split()
=> Importer fix

AUTHORS, container/config.py, test/roles/validate-config/files/container.yml, test/tests/validate_config.py
=> Support ${PWD} in volumes

container/docker/templates/conductor-dockerfile.j2
This pull requests modifies the template `conductor-dockerfile.j2`
including a block that installs the necessary packages for a RHEL
container.
=> Adds support for RHEL as a conductor container

container/core.py, container/docker/engine.py
=> Include service volumes during build

container/cli.py, container/config.py, container/docker/engine.py, container/utils/__init__.py
Replaces my hackery with the more elegant method suggested by @j00bar.
=> More elegant approach to preserving config key order.

.travis.yml, container/core.py, container/docker/engine.py, container/docker/importer.py, container/docker/templates/conductor-dockerfile.j2, container/engine.py, container/k8s/base_engine.py, test/tests/validate_config.py
=> Fixes to prep for 0.9.1

container/cli.py, container/config.py, container/core.py, container/docker/engine.py
Adds a `conductor` section to `settings` in `container.yml` with support for the following attributes: `base`, `volumes`, `environment`.
=> Adds conductor section

container/cli.py
Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>
Like this:
```
$ PYTHONPATH=/path/to/ansible-container python3 -m container.cli --debug build
```
Shall I also update docs?
=> add a way to run a-c from git

container/templates/init/ansible-requirements.j2.txt, container/templates/init/container.j2.yml, container/templates/init/requirements.j2.yml
- Nit Pull Request
Added an additional newline on the init templates for a new project that resolves a small nit that these files if not modified will not have an extra newline and show up on GitHub as missing one
=> Add End of File Newline on Templates

AUTHORS, container/docker/templates/conductor-dockerfile.j2
Fixing broken conductor builds. We're hitting the following issue with pynacl: https://github.com/pyca/pynacl/issues/298
=> Fixes pynacl install during conductor build

container/docker/templates/conductor-dockerfile.j2
Fixes #592. Verbose flag might be excessive, but let me know.
=> Fixes #592 tgz getting downloaded as a directory

docs/rst/reference/build.rst
Fixes #581
Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>
Document pip issue when installing python modules on overlay graph backend.
=> document "Directory not empty" pip error

AUTHORS, proposals/secrets.md
@ehelms 
@j00bar 
Adding the proposal we spoke of the other day in IRC.
=> Adds Secrets proposal

AUTHORS, container/cli.py, container/docker/engine.py, container/templates/init/container.j2.yml, docs/rst/container_yml/reference.rst, docs/rst/reference/deploy.rst, docs/rst/reference/destroy.rst, docs/rst/reference/push.rst, docs/rst/reference/restart.rst, docs/rst/reference/run.rst, docs/rst/reference/stop.rst
=> Fixes roles_path implementation

proposals/statefulsets.md
- Proposal Pull Request
Proposal for ansible-container to support Stateful Sets in k8s and OpenShift environments. I figured I'd start with a proposal this time instead of code.This is supported on k8s 1.5+ and already exists within the Ansible Kubernetes modules. I believe this should be fairly simple for me to implement but I think supporting this and the syntax are worth a discussion.
=> Add Stateful Sets proposal

AUTHORS, container/core.py, container/docker/engine.py, container/engine.py, container/k8s/base_engine.py
Fixes #630
When `registry_prefix` is set to '', don't override it with `project_name`.
=> When registry_prefix == '', don't override with project_name

container/docker/engine.py
Not all from image values will contain a tag.
=> When pulling images, default tag to 'latest'

AUTHORS, container/docker/templates/conductor-dockerfile.j2
=> Fix chardet package conflict

container/docker/engine.py
Fixes `${PWD}` not being resolved when used in`settings.volumes` .
=> Allow for ${PWD} in settings.volumes

container/cli.py, container/docker/engine.py, container/templates/build-docker-compose.j2.yml, container/templates/listhosts-docker-compose.j2.yml, docs/rst/reference/build.rst, docs/rst/reference/deploy.rst, docs/rst/reference/destroy.rst, docs/rst/reference/push.rst, docs/rst/reference/restart.rst, docs/rst/reference/run.rst, docs/rst/reference/stop.rst
Allow specifying multi roles paths through the command line or conductor settings.
=> Support multiple roles paths

AUTHORS, docs/rst/reference/install.rst, docs/rst/roles/access.rst
Attempt to improve docs for the `install` command.
=> Adds install docs

container/core.py, container/docker/engine.py, container/docker/secrets.py
Fixes issues found while testing secrets:
- During `run`,  `--ask-vault-pass` failed to prompt for a password 
- When there was more than one secret, Docker engine failed to write all secrets to disk
=> Fixes bugs related to secrets

container/core.py
Reverts a change made in #678 
Closes #694
=> Removes service level defaults from cache fingerprint

AUTHORS, CHANGELOG.rst, ROADMAP.rst, closed_pulls.py, docs/_themes/srtd/footer.html, docs/rst/roadmaps/index.rst, docs/rst/roadmaps/roadmap_0_9_0.rst, docs/rst/roadmaps/roadmap_1_0_0.rst
- Adds changelog to provide release notes
- Updates roadmap docs to include what happened in 0.9.0 and major changes planned for 1.0.0
=> Adds changelog

ROADMAP.rst
Update ROADMAP.rst to reflect the correct release for the link to the 1.0.0 roadmap
Update ROADMAP.rst to reflect the correct release for the link to the 1.0.0 roadmap
=> Update ROADMAP.rst to reflect 1.0.0 correctly

AUTHORS, docs/rst/container_yml/template.rst
Updating to reflect current state of template rendering pos 0.9.0.
=> Updates Jinja template doc

AUTHORS, container/config.py, container/core.py, container/docker/config.py, container/docker/engine.py, container/docker/secrets.py, container/k8s/base_deploy.py, container/k8s/base_engine.py, container/k8s/config.py, container/utils/__init__.py, docs/rst/container_yml/index.rst, docs/rst/container_yml/pods.rst, docs/rst/container_yml/reference.rst, docs/rst/reference/build.rst
Implements support for multiple containers per pod as proposed by #639
=> Multi-container implementation

AUTHORS, CHANGELOG.rst, ROADMAP.rst, docs/rst/roadmaps/index.rst, docs/rst/roadmaps/roadmap_0_9_2.rst, docs/rst/roadmaps/roadmap_1_0_0.rst, docs/rst/roadmaps/roadmap_1_1_0.rst
- Creates 0.9.2, 1.0.0, 1.1.0 roadmaps
- Adds pre-bake to the changelog
=> Changelog and Roadmap updates
