ansible/ansible-container

setup.py

ran into following error:
-----
ansible-container build
No module named docker.engine
-----
Found that the module was missing in the setup.py

Add container.docker module to setup.py

---

container/templates/ansible-dockerfile.j2
container/templates/build-docker-compose-v1.j2.yml
container/templates/build-docker-compose.j2.yml
container/templates/listhosts-docker-compose-v1.j2.yml
container/templates/listhosts-docker-compose.j2.yml

This removes the volume bind of the host's docker executable to the build container. We hit multiple examples where the host's docker daemon is using a storage driver not compatible with the Python 2.7 (Debian jessie) base image container. Installing docker make the image build a little bit slower, but it's the only way to insure docker works correctly.

Install docker in the ansible build container

---

setup.py

Fixes #41. The container submodules were not being picked up by `python ./setup.py install`.

Fix #41 missing container submodules

---

README.md

Trying to clone the repo without an url scheme leads to an error, because git defaults to ssh: 
```
git clone git@github.com:ansible/ansible-container.git
Cloning into 'ansible-container'...
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
It works however, when you try to clone via https instead of ssh.

Add missing https url-scheme to the upstream git repo-url

---

container/cli.py
container/docker/engine.py
container/engine.py

Allow the user to set a custom repository name. Defaults to registry username. Needed in the case of the GKE where the repository name must be the project ID.

Add --repository to push subcommand.

---

example/ansible/container.yml

When the port is defined as '- 8080', compose maps it to a random port on the host. Not very useful, and leaves the demo broken.

Add host port for django, otherwise the demo doesn't work.

---

container/utils.py
test/unit/container/test_utils.py

Errors out if main.yml or container.yml is missing when running
`ansible-container build`

Error out if main.yml is missing

---

container/docker/engine.py
test/integration/test_slow.py

This fixes #111. By default images are not being exported and flattened, which makes each build dependent on the prior build, in which case the prior image cannot be removed. 
You can run `ansible-container build --flatten` to break the dependency chain. For example, notice in the output below (created with --flatten) that 'Removing previous build' gets executed. This is because an export/import of the image occurred and there is no longer a dependency on the previous build.
```
ansible-container_1  |
ansible-container_1  | PLAY RECAP *********************************************************************
ansible-container_1  | django                     : ok=15   changed=4    unreachable=0    failed=0
ansible-container_1  | gulp                       : ok=13   changed=4    unreachable=0 …
```

Don't remove prior image if it is child to new image.

---

container/templates/build-docker-compose.j2.yml
container/templates/listhosts-docker-compose.j2.yml

Add a `:Z` suffix so that the ansible build container can
actually see the ansible-container and docker-certs
working directories.
https://docs.docker.com/engine/tutorials/dockervolumes/#volume-labels

Allow ansible-container to mount with SELinux

---

docs/rst/reference/build.rst

- New Module Pull Request
```
```
ansible-container build -h
````
--no-purge-last  By default, Ansible Container will remove the previously
built image for your hosts. Disable that with this flag.
````

Option name is different in the doc

---

container/cli.py
container/docker/engine.py
container/engine.py
container/templates/stop-docker-compose.j2.yml
test/integration/projects/minimal_sleep/ansible/container.yml
test/integration/projects/minimal_sleep/ansible/main.yml
test/integration/projects/minimal_sleep/ansible/requirements.txt
test/integration/test_fast.py
test/integration/test_slow.py

Issue #91 and #131 talked about the need of deploying the application in detached mode, which is what I have attempted to do in this PR.
Since `docker.engine.orchestrate` calls `get_config_for_...`, which in turn calls `orchestrate` again, I had to remove `self.params['detached']` so that `get_config_for_...` does not run in detached mode; I set a `detached` flag to True, which I use in the end before `command.up` is executed to pass `-d` to `command.up`
```
Before:
usage: ansible-container [-h] [--debug] [--engine ENGINE_NAME]
[--project BASE_PATH]
{run,help,shipit,init,build,push} ...
ansible-container: error: unrecognized arguments: -d
```
```
After:
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
Deploying application in …
```

implement detached mode for run, fix #131

---

container/docker/engine.py

Fixes #171 build- puts invalid command value in image Config.Cmd during post build steps. 
In the post build steps, if the service command is an array, joins the array elements into a string. 
Prior to this fix the Config.Cmd was producing:
```
"Cmd": [
"/bin/sh",
"-c",
"['/root/start.sh', 'now']"
],
```
With the changes included in this PR the Config.Cmd is set to:
```
"Cmd": [
"/bin/sh",
"-c",
"/root/start.sh",
"now"
],
```

In post build steps always send string to image Cmd

---

container/cli.py
container/docker/engine.py
test/integration/test_slow.py

- Implemented killing of running services by passing `ansible-container stop --force <service>`
- Added tests for this behavior
```bash
Killing ansible_webclient_1 ... done
Killing ansible_webserver_1 ... done
```

implement force stopping containers, add tests

---

Makefile
test/run.sh

Fixes the following:
- Adds develop command to Makefile
- Points test command in Makefile to ./test/run.sh
- In the ./test/run.sh adds the --flatten option to build of test container

Makefile adjustments

---

container/cli.py
container/docker/engine.py
container/engine.py
container/templates/restart-docker-compose.j2.yml
test/integration/test_fast.py
test/integration/test_slow.py

Supersedes #158 
This implements `ansible-container restart <service>` command.
Added tests.
```bash
Restarting ansible_webclient_1 ... done
Restarting ansible_webserver_1 ... done
```

implement ansible-container restart, add tests

---

container/cli.py
container/config.py
container/docker/engine.py
container/engine.py
container/templates/ansible-container-inventory.py
container/utils.py
test/integration/projects/vartest/ansible/container.yml
test/integration/projects/vartest/ansible/devel.txt
test/integration/projects/vartest/ansible/devel.yaml
test/integration/projects/vartest/ansible/main.yml
test/integration/projects/vartest/ansible/requirements.txt
test/integration/test_slow.py
test/run.sh
test/unit/container/test_config.py

Per issue #120 adds support for jinja2 style variables in container.yml.
Modifies AnsibleContainerConfig to support Jinja2 template rendering. AnsibleContainerConfig resolves variable values and performs the expansion on initialization. It uses the following order of precedence when resolving variables: 
- environment vars (any environment vars starting with AC)
- variables provided in a file using new *--var-file* option
- and finally a new 'defaults' section added to the top level of container.yml.
For example, given the following:
- environment var AC_DEBUG=1
- devel.yml as a var file that defines debug=0
- defaults section in container.yml defining debug: 2
The environment variable would win, giving *debug* a value of 1.
Here is an example container.yml taken from …

Jinja2 template rendering in container.yml

---

container/templates/build-docker-compose.j2.yml

Fixes #126. List of volumes from --with-volumes was not rendered correctly in the docker-compose template used by the build command.

Correctly format list of volumes for `build` command

---

container/docker/engine.py

Put redundant code under `def bootstrap_env` so `orchestrate`, `terminate`, `restart` functions could reuse it.

refactor orchestrate, terminate, restart functions

---

container/templates/ansible-dockerfile.j2

Fix #208 
This is a follow up to the fix for #208. Updated the Ansible version to 2.1.1.0 in the Ansible Container Builder image, but did not update the Dockerfile template used by the `--local-build` option on the `build` command. This PR contains the update.

Bump Ansible version to 2.1.1.0

---

container/shipit/base_engine.py
container/shipit/openshift/engine.py

Finally tracked down the fix for #174 - shipit modules not being copied. If Ansible Container is installed via pip, the Ansible modules are not included, and so there are no modules to copy. 
Added __init__.py in the modules subdirectory, and that seems to fix it. At least it works when installing wiht pip using the following:
```
pip install --upgrade  git+https://github.com/chouseknecht/ansible-container.git
```

Shipit fails to copy Ansible modules to library path

---

container/shipit/openshift/modules/oso_api.py

In 71b1db3 the OriginAPIException class was removed. This is an
attempt to clean up any remaining references so that the code won't
error out when this is encountered.

openshift: remove references to OriginAPIException

---

container/cli.py
container/engine.py
container/templates/build-docker-compose.j2.yml
container/templates/listhosts-docker-compose.j2.yml
docs/rst/reference/build.rst
docs/rst/reference/run.rst
docs/rst/reference/shipit/kube.rst
docs/rst/reference/shipit/openshift.rst

During the `build`, `run` and `shipit` commands, to get the list of hosts touched by the playbook we invoke Ansible playbook in the build container with the `--list-hosts` option.  For this to work it needs to parse and interpret `main.yml` which may require access to the same `--with-volumes` and `--with-variables` options used to run `build`.

Add --with-volumes and --with-variables to run and shipit.

---

.gitignore
container/config.py
container/docker/engine.py
container/templates/ansible-dockerfile.j2
container/templates/ansible.cfg
container/templates/ansible.j2.cfg
container/templates/ansible/ansible.j2.cfg
container/templates/ansible/requirements.j2.yml
container/templates/builder.sh
docs/rst/index.rst
docs/rst/reference/run.rst
docs/rst/reference/shipit/kube.rst
docs/rst/reference/shipit/openshift.rst
docs/rst/roles/existing.rst
docs/rst/roles/galaxy.rst
docs/rst/roles/index.rst
test/integration/projects/requirements/ansible/container.yml
test/integration/projects/requirements/ansible/main.yml
test/integration/projects/requirements/ansible/requirements.txt
test/integration/projects/requirements/ansible/requirements.yml
test/integration/test_slow.py

Add support for ansible/requirements.yml per #221. Adds requirements.yml to `ansible` directory. If user adds roles, they will be automatically installed to /etc/ansbile/roles. Latest build container image includes /etc/ansible/roles directory and /etc/ansible/ansible.cfg with roles_path=/etc/ansible/roles.
Added a default ansible.cfg to `ansible` directory. Defaults roles_path=/etc/ansible/roles. User can of course override this. 
Added copious amounts of documentation under rst/roles regarding how to use existing roles from file system or VCS.

Feature/support requirements.yml

---

container/docker/engine.py
container/templates/ansible-dockerfile.j2
container/templates/builder.sh
container/templates/wait_on_host.py
test/integration/test_slow.py

- Adds wait_on_host.py script to build container.
- Updates builder.sh to call wait_on_host.py for each host that will be touched by the playbook.
- Prevents playbook execution from starting until all of the hosts are in a running state.
- Fixes #234

Prevent build container race condition

---

container/docker/engine.py

The issues fixed by this pull request (as a single PR, as they all touch the same code) are:
- images may not have a custom entrypoint specified (it is ignored)
- images may not have a command specified as a list (only as a string that gets passed to the shell)
- images have labels left over from `docker-compose` which means containers created from them get destroyed at every `ansible-composer` run

A bunch of fixes in final image metadata

---

container/templates/ansible-dockerfile.j2

In 9deb3eb we moved to /usr/bin/ansible-playbook
Let's ease the transition on people using <9deb3eb code
by symlinking to the new place

builder: add symlink to ease transition

---

test/utils/tests/integration.sh

On my laptop, I was unable to run the slow integration test suite due to the value of the default timeout (30 seconds).
This pull request allows to override this timeout using the `AC_SLOW_TEST_TIMEOUT` environment variable is used (without modifying the local repository). 
I have synchronized/updated both [CONTRIBUTORS.md](https://github.com/ansible/ansible-container/blob/5869146e2e3bf44431a1bb2c10dcb7a541125750/CONTRIBUTORS.md#running-tests) and [test/README.md](https://github.com/ansible/ansible-container/blob/5869146e2e3bf44431a1bb2c10dcb7a541125750/test/README.md) (see https://github.com/ansible/ansible-container/commit/aa7b86722eb257b30ac7468eb724079e9487e10b), let me know if you prefer:
* keep `CONTRIBUTORS.md` only and remove `test/README.md`
* keep `test/README.md` and update …

 Allow to override the default timeout used for slow integration tests

---

AUTHORS
pre-commit

Add pre-commit script. Contributors can copy to .git/hooks/pre-commit, and it will automatically update AUTHORS.

Add pre-commit script and update AUTHORS

---

container/cli.py

The `push` command uses`listhosts` when determining which images to push, so it needs access to `--roles-path` and `--with-volumes`.
Fixes #255

Add common options to push command

---

CONTRIBUTORS.md
test/README.md

The content of [test/README.md](https://github.com/ansible/ansible-container/blob/5869146e2e3bf44431a1bb2c10dcb7a541125750/test/README.md) was duplicated in [CONTRIBUTORS.md](https://github.com/ansible/ansible-container/blob/5869146e2e3bf44431a1bb2c10dcb7a541125750/CONTRIBUTORS.md#running-tests) but since https://github.com/ansible/ansible-container/commit/aa7b86722eb257b30ac7468eb724079e9487e10b, content has diverged.
This pull request move the up-to-date documentation related to tests in `test` directory.

Keep info related to tests in test/README.md

---

container/templates/ac_galaxy.py
docs/rst/roles/access.rst

This relates to the role testing issue (#271). In order to test a role it has to go through the install process, which means downloading it from GitHub, even though the role already exists on the local file system. The role has to be downloaded and applied to the local *ansible* project, updating `container.yml`, `main.yml` and `requirements.yml`.
To invoke the download we pass a commit hash as the version. The install sees the hash and works, however the hash does not get added to the new `requirements.yml` entry. This PR fixes this by adding scm, src, version and name attributes to the entry. Only attributes containing a value are added.

Complete requirements.yml

---

container/templates/ac_galaxy.py

Fixes #270. When defaults/main.yml is empty, return a CommentedMap() object rather than an empty {}. This change allows the [.insert()](https://github.com/ansible/ansible-container/blob/develop/container/templates/ac_galaxy.py#L156) to work, and prevents `!!omap` from appearing in the output.
Already pushed new version of [0.3 build container](https://hub.docker.com/r/ansible/ansible-container-builder/tags/) that includes this change.

When defaults/main.yml empty return ruamel.ordereddict

---

container/templates/ac_galaxy.py

When a role that is not *container enabled* is encountered by ac_galaxy a warning is thrown. The current warning actually has a bug in it, as it passes the role object into the format rather than the role's name attribute resulting in a message that looks like this: "Role <ansible.galaxy.role.GalaxyRole object at 0x7f386ab6aed0> is not Ansible Container enabled"
This change fixes the format bug, and alters the text to makes it clear that even though the role is NOT container enabled, it will still be added to *requirements.yml*. Previously it was unclear if any action was taken with the role, and you were left wondering if perhaps it was skipped altogether.

Make warning regarding non-container roles more explicit and clear.

---

container/shipit/kubernetes/deployment.py
container/shipit/openshift/deployment.py

Fixes #253 and replaces #277.
When building configuration files the each port in the ports list is a dict, otherwise it is an int. Thus when looking for an existing port we need to take into account the list element's type. Applies to both *kube* and *openshift*.

Fix port comparison error in deployment module

---

container/config.py
requirements.txt

Using Python 3, one unit test fails:
```
=========================== short test summary info ============================
FAIL test/unit/container/test_config.py::TestAnsibleContainerConfig::test_should_parse_json_file
=================================== FAILURES ===================================
____________ TestAnsibleContainerConfig.test_should_parse_json_file ____________
[...]
try:
config = json.loads(data)
except Exception as exc:
>               raise AnsibleContainerConfigException(u"JSON exception: %s" % str(exc))
E               container.exceptions.AnsibleContainerConfigException: JSON exception: the JSON object must be str, not 'bytes'
container/config.py:208: AnsibleContainerConfigException
```

Python 3 compat: unit tests

---

test/run.sh

Exit status of `test/run.sh` should not be 0 when an `ansible-container` command fails.
`nounset` is an added bonus.

Don't ignore failures of ansible-container commands

---

container/docker/engine.py

Using Python 3, `all_hosts_in_orchestration` method returns a `dict_keys` instead of a list, the following error occurs:
> TypeError: can only concatenate list (not "dict_keys") to list

Ensure all_hosts_in_orchestration return a list

---

container/cli.py
test/integration/test_fast.py

Using Python 3, the `test_no_command_shows_help` test fails due to the updated behavior of `argparse` module. The `parser.parse_args()` doesn't raise an error when a command isn't provided. See https://bugs.python.org/issue9253.
```
def test_no_command_shows_help():
env = ScriptTestEnvironment()
result = env.run('ansible-container', expect_error=True)
>       assert result.returncode == 2
E       assert 1 == 2
E        +  where 1 = <scripttest.ProcResult object at 0x7f9807e44438>.returncode
```

Python 3 compat: handle new behavior of argparse

---

.gitignore
AUTHORS
test/build-test-img/README.md
test/build-test-img/ansible/container.yml
test/build-test-img/ansible/main.yml
test/build-test-img/ansible/requirements.txt
test/build-test-img/ansible/requirements.yml
test/build-test-img/ansible/templates/pyinstall.sh.j2
test/build-test-img/run.sh
test/local/ansible/container.yml
test/local/ansible/main.yml
test/local/ansible/templates/entrypoint.sh.j2
test/requirements.txt
test/run.sh
tox.ini

Use *tox* inside the testing container and test with Python 2.7, 3.4, and 3.5. 
- created a Centos 7 base image with all the needed packages, shellcheck, pyenv and Python 2.7.12, 3.4.5, and 3.5.0. The image is on Docker Hub as ansible/ansible-container-testing. 
- added test/build-test-img project to use for rebuilding the image
- tests are executed the same as before by running ./test/run.sh
- the same script and process is used locally and in Travis
Current py34 and py35 are commented out in *tox.ini* because there are still syntax issues that need to be fixed. However, py27 completes the tests successfully.

Use tox and pyenv inside the test container

---

container/cli.py
container/docker/engine.py
container/engine.py
container/templates/ac_galaxy.py

Fix python 3 compat, see PEP 3110.

Python 3 compat: use 'as' instead of comma after 'except' keyword

---

container/shipit/openshift/route.py

When creating the shipit role and `options: openshift: state` was set to`absent`, the route config was garbled. This PR fixes it.

Fix OpenShift route state.

---

container/docker/engine.py
container/engine.py

The first commit fixes an erroneous message (`Orchestrated hosts: <filter object at 0x7f9e20150978>`).
The second commit modifies the type returned by `[Base]Engine.hosts_touched_by_playbook`: this method returns now a `frozenset` instead of a list. The modified code was using a list, converted to a set, then converted to list and returned an iterator.

Improve log message, use a a set instead of a list

---

container/templates/builder.sh

Configuration file `requirements.txt` was not being run by builder.sh.
Changed the shell test to also match the `requirements.yml` code.
Fixes #306 
Run pip on ./requirements.txt.
Match the test format for the rest of the file, and use the same path as the requirements.yml stanza.

run pip on ./requirements.txt

---

.travis.yml
AUTHORS
container/docker/engine.py
container/templates/builder.sh
test/local/ansible/requirements.txt

- Remove docker 1.11.2 downgrade in .travis.yml. By default 1.12.0 gets installed.
- Fixes #310

Use Docker 1.12 to run integration tests

---

docs/rst/installation.rst

The URL https://galaxy.ansible.com/ansible/secure-docker-daemon for securing docker daemon on here https://docs.ansible.com/ansible-container/installation.html#securing-docker-daemon-with-tls gives `404 not found`.
This patch links it to the Github Repo rather.

Fix role-secure-docker-daemon link

---

AUTHORS
container/docker/engine.py

Fixes #147 by using env var DOCKER_CLIENT_TIMEOUT when instantiating the Docker client. If not set, defaults to docker.constants.DEFAULT_TIMEOUT_SECONDS

Use DOCKER_CLIENT_TIMEOUT env var when instantiating Docker client

---

container/docker/engine.py

Refining fix for #147.
Addresses issue raised on #315 
- Adds support for COMPOSE_HTTP_TIMEOUT, as it appears compose is deprecating support for DOCKER_CLIENT_TIMEOUT
- Casts value received from either COMPOSE_HTTP_TIMEOUT or DOCKER_CLIENT_TIMEOUT to int
- Gracefully handles errors arising from a non-integer value

Improved client timeout

---

container/cli.py

Because of a discrepancy between the name of the flag (`--no-purge-last`) and that of the attribute (`purge_last`) checked in `post_build()` this command line argument had no effect.
This change makes sure that the boolean flag is stored with the correct attribute name.
Sorry for the lack of a test, but my non-existing Python coding skills prevent me from writing one.

Fix parsing of the --no-purge-last argument

---

AUTHORS
update-authors.py

The update script for the AUTHORS file was ignoring the number of files,
this commit changes it to count files in the author scoring and switches
to use `defaultdict` instead of setdefault.

Fixup of `update-authors.py` script

---

container/engine.py

In Python3 there's no urllib.basejoin, so use the `six.moves` package to find the right function in Py2 and Py3.
```
$ ansible-container init chousenecht.django-gulp-nginx
module 'urllib' has no attribute 'basejoin'
[nonzero exit]
```

Fix use of urllib.basejoin to work on Python3 as well

---

AUTHORS
update-authors.py

Commits on Py3-only hosts would fail if the `pre-commit` scripts were enabled with:
```
Traceback (most recent call last):
File "update-authors.py", line 17, in <module>
log_entries = git_log.strip().split('\n')
TypeError: a bytes-like object is required, not 'str'
```

Python 3-ify the `pre-commit` script so it works on py3-only hosts

---

container/docker/engine.py
container/engine.py
container/shipit/base_engine.py

Adds --local-images option to `shipit`. This is specifically to support the [minishift](https://github.com/minishift/minishift) use case where images are built with the Docker daemon running on the minishift VM, and then used locally by the OpenShift instance without having to push them into the registry.

Adds --local-images option to `shipit`

---

docs/rst/getting_started.rst
docs/rst/index.rst
docs/rst/openshift/containers.rst
docs/rst/openshift/index.rst
docs/rst/openshift/minishift.rst
docs/rst/reference/shipit/kube.rst
docs/rst/reference/shipit/openshift.rst

- Modifies the *Install and Configure OpenShift* guide to include two options: *Using Containers*, and *Minishift*. The *Minishift* section is new, and provides a how-to guide for creating and using a Minishift instance. 
- Fixes #341 
- Adds --local-images to shipit command reference

Adds Minishift documentation.

---

docs/rst/container_yml/template.rst

Typo, `var_files` isn't a thing. But `vars_files` is. Discovered via [this stackoverflow question](http://stackoverflow.com/questions/41384032/ansible-container-variables-in-playbook).

var_files -> vars_files

---

container/cli.py
docs/rst/container_yml/template.rst

There was a simple typo in the error log message, which was bugging me. I tried to find out whether there was some rationale for the use of `containery` instead of `container`, but the internet fell silent. 
This doesn't fix anything that was previously broken, but makes the error message English.

Brucellino patch typo containery

---

AUTHORS
requirements.txt

- Bumping requests version to match [docker/docker-py](https://github.com/docker/docker-py/blob/1.10.6/requirements.txt#L1)
- Attempting to set a minimum for Jinja2 and PyYAML, rather than a hard version.
Fixes #337

Attempting to close #337

---

container/docker/engine.py
container/exceptions.py

If `ansible-playbook --list-hosts main.yml` fails, Ansible Container keeps running. It errors later with an unrelated and confusing message, leaving the user confused. The only way to then find the actual error is to run the command again with the `--debug` option, wait for the error, and then scroll back through screens of output.
This change inspects the stdout lines from the above command looking for 'exited with code 0'. If that does not exist, then something is wrong, most likely with they playbook's syntax. The stdout from the command is logged to the console, and execution halts, leaving the user alerted to exactly what went wrong.

Surface --list-host errors

---

container/cli.py
container/docker/engine.py
container/engine.py
container/shipit/base_engine.py

Kind of touches on #125 
This PR adds the `--tag` option to the `push` subcommand, allowing you to specify a custom tag for your image. This custom tag will be applied to your image, and then that tag will be pushed to your repository (instead of the default, `image_buildstamp`).
Before:
```
$ ansible-container push --push-to ansibleapp
Pushing to "docker.io/ansibleapp
Attaching to ansible_ansible-container_1
Cleaning up Ansible Container builder...
Tagging docker.io/ansibleapp/elk-ansibleapp-elasticsearch
Pushing docker.io/ansibleapp/elk-ansibleapp-elasticsearch:20170201164646...
The push refers to a repository [docker.io/ansibleapp/elk-ansibleapp-elasticsearch]
Preparing
Layer already exists
20170201164646: digest: …
```

Custom tagging for push and shipit

---

AUTHORS
docs/rst/reference/push.rst
docs/rst/reference/shipit/kube.rst
docs/rst/reference/shipit/openshift.rst

Follow-up to #372. Adds reference docs for `--tag` option on both `push` and `shipit` commands.

Add reference docs for --tag

---

docs/rst/container_yml/template.rst

The documentation is currently mentioning that one cannot use a Vault with Ansible Container.
This change replaces this part of the documentation with 2 ways of using a vault by using the regular --vault-password-file options

Document how to use a Vault with build command

---

container/cli.py

When running  `ansible-container build` on a low-memory machine, it fails with a `MemoryError` with nothing displayed to the user. That's because `str(e)` returns an empty string.
Changed to provide a meaningful output.
Before:
```
Starting Docker Compose engine to build your images...
Attaching to ansible_ansible-container_1
#
```
After:
```
Starting Docker Compose engine to build your images...
Attaching to ansible_ansible-container_1
Execution failed with <type 'exceptions.MemoryError'>
#
```

Fixed no message displayed on an Exception.

---

AUTHORS
container/__init__.py
container/cli.py
container/conductor-requirements.txt
container/conductor/__init__.py
container/conductor/cli.py
container/conductor/config.py
container/conductor/core.py
container/conductor/docker/__init__.py
container/conductor/docker/deploy.py
container/conductor/docker/engine.py
container/conductor/engine.py
container/conductor/loader.py
container/conductor/utils.py
container/conductor/visibility.py
container/config.py
container/core.py
container/exceptions.py
container/temp.py
container/utils.py
container/visibility.py
requirements.txt
setup.py

This change migrates much of the project logging to the [structlog](https://structlog.readthedocs.io/en/stable/) library to help make information coming from different places inside ansible-container, and make it easier to attach extra information to logs. For example, as a dev you can make your logs more useful by writing code like `log.info("Pulling dependent images", images=["f102e1f66597", "4a07b2d390de", "88e169ea8f46"])`. For users in debug mode, that will be colorized with the message in bold and the extra data in a less obtrusive color for easy skimming. In normal usage, all logs will be dumped to JSON and output so they can be consumed by other tools. 
```
2017-03-20T11:04:29.077045 Loading engine capabilities …
```

Log refactor

---

test/roles/validate-build-and-import/tasks/main.yml

`env` lookup returns an empty string when the environment variable isn't defined, hence `path` parameter wasn't omitted and relative path was used.
The exception was:
```
docker.errors.APIError: 500 Server Error: Internal Server Error (\"create ansible.jpz85xs2ubuntu/test-ubuntu: \"ansible.jpz85xs2ubuntu/test-ubuntu\" includes invalid characters for a local volume name, only \"[a-zA-Z0-9][a-zA-Z0-9_.-]\" are allowed. If you intented to pass a host directory, use absolute path\")"
```

Env lookup always returns a string

---

setup.py

I encountered this problem while testing #412, environment markers should not be ignored.

Check environment markers before installing a dep

---

container/config.py
container/docker/templates/conductor-dockerfile.j2
container/templates/init/container.j2.yml

- Installs gcc when Debian.
- Fixes `config.py` not returning a valid path when `deployment_output_path` = `./ansible-deployment`
- A little clean up in the `init/container.j2.yml` template

Install gcc when conductor is Debian

---

container/docker/templates/conductor-dockerfile.j2

Dockerfile fails to build when using Fedora as distro due to trying to install the unnecessary epel-release package.
```
```

Fedora systems do not have or need epel-release

---

AUTHORS
container/cli.py
container/core.py
container/docker/templates/conductor-dockerfile.j2
docs/rst/reference/build.rst

- Remove `lsb_release` from conductor and force Ansible to read `/etc/lsb-release`
- Replaces `--python-interpreter` with `--use-local-python` option. If True, will prevent mounting `/usr` from conductor to `/_usr` in the target.

Make life better for Xenial users

---

container/core.py
container/docker/templates/conductor-dockerfile.j2

Fedora-based conductor shoud use dnf and install additional package (redhat-rpm-config) -
its required to compile cryptography

Conductor image: support fedora

---

container/docker/importer.py

`ansible-container import --bundle-files ../demo` results in an error regarding missing `./roles/demo/files` path. This PR insures the path gets created prior to copying files.

When --bundle-files, create files path

---

container/docker/engine.py

Use introspection to remove service attributes that should not be passed to `docker run`.
Fixes #478

Use introspection to remove invalid kwargs from container run

---

container/core.py
container/docker/templates/conductor-dockerfile.j2

This change uses `dpkg-architecture -qDEB_HOST_MULTIARCH` to determine the current architecture and adjusts the LD_LIBRARY_PATH accordingly when running python on the container build. This requires a new package dependency in the Dockerfile, which is also added in this PR.
For an in-depth analysis check the analysis section of the referenced ticket.
Fixes #480

Fixes builds for debian/ubuntu based images (#480)

---

container/cli.py

Python 3.5 b64decode returns a byte-string, rather than a string.

Decode byte-string returned by base64.b64decode()

---

container/core.py

properly quote inventory and playbook path when calling ansible-playbook
otherwise you get funny errors if the path contains spaces or other "special" characters.
example:
```
ERROR! the playbook: Org/some-container/ansible-deployment/hosts could not be found
```
as the original path was:
```
/home/user/Example Org/some-container/
```

properly quote inventory and playbook path when calling ansible-playbook

---

container/templates/init/container.j2.yml
docs/rst/getting_started.rst

Fixes #493 
The new `container.yml` delivered by `ansible-container init` matches the one in the docs and is buildable and runnable.

Updates docs and starter container.yml delivered by init to match each other.

---

container/k8s/base_engine.py

The documentation shows that the registry does not require a trailing slash or the namespace. When joining URLs using urljoin if there is no trailing slash the namespace gets overwritten by the tag
There was a bug in the way that URLs were joined using urljoin. Added a conditional to add this logic in for namespaces for k8s deployments
Fixes #489

Fixed urljoin bug in k8s deployment

---

AUTHORS
container/config.py
container/core.py
container/docker/engine.py
test/tests/validate_config.py

Fixes #514
- Fixes `--with-variables`.  When variables are passed on the command line, they are now added to the conductor's environment
- In `config.py`, check if a template string results in an AnsibleUnsafeText object. If so, convert it to a string. This happens when a filter is used inside a template. In this particular case, it's the `lookup()` filter.

Fix for #514

---

container/docker/engine.py

Fixes #467 
Anytime a playbook is executed, `/src` gets bind mounted to a temp directory, which seems to be causing issues on Ubuntu. The quick fix is to always run with `privileged=True`, as that's what fixed `build`.

Always run conductor privileged

---

container/docker/engine.py

Fixes #519 
When calculating the tag for a given service, convert both the project name and service name to lowercase.

Image tags should be lowercase

---

container/docker/engine.py
container/utils/galaxy.py

- If a service does not have a `roles` directive, then pass the `from` value as the `image` to Ansible playbook that runs the application, and allow the `docker_service` module to pull the image.
- Warns that it will attempt to pull the image
- Fixes parsing of `meta/container.yml`.
- Adds a new service with the same name as the role, since the meta data no longer contains a service name.
- Only adds a `roles` directive to the new service, ignoring all other directives

Enable image pulls, and fix role install

---

container/docker/engine.py

Fixes #524 - build --with-volumes does not mount the volumes in the conductor
This should also fix --with-volumes for all other commands where it is accepted on the command line

implements the --with-volumes cli argument

---

AUTHORS
container/cli.py
container/config.py
container/core.py
container/docker/engine.py

- Whenever we're working with volumes, we should account for user variables and `~` in the src path.
- Whitelist `expose` directive
- Build services in the expected order, top->bottom.

For volume src path, normalize and expand user vars

---

container/config.py
container/core.py
container/engine.py

After fixing the service order returned by the decoded configuration in cli.py, the `run` playbook broke. For some reason ordered dictionaries are being returned as arrays. Rather than fight with YAML output, removing unnecessary ordered dictionaries.

Fix broken playbooks

---

container/cli.py

The --with-volumes option should be usable with `stop` and `destroy` commands as ansible.cfg is taken in account when those commands are invoked .
I am using Ansible with vault. The vault file is actually a shell script that relies on (credstash)[https://github.com/fugue/credstash]:
```
[defaults]
vault_password_file = get-vault-key.sh
```
```
#!/usr/bin/env bash
ENV_DATA=./env-data
if [ -f ${ENV_DATA} ]
then
. "${ENV_DATA}"
else
exit 1
fi
credstash -t ${REGION}-CredStash-GumRef-${TEAM} get ansible-vault-key
```
We are grabbing the ansible vault secret from AWS DynamoDB so we need AWS cli credentials to be mounted in the conductor container. In production (Jenkins CI/CD) we do not have issues with AWS credentials because we are using IAM roles. But on a developer …

#535 BugFix - Fixing --with-volumes for stop and destroy

---

.travis.yml
conductor-requirements.txt
container/cli.py
container/config.py
container/core.py
container/docker/config.py
container/docker/engine.py
container/engine.py
container/k8s/base_config.py
container/k8s/base_deploy.py
container/k8s/base_engine.py
container/k8s/config.py
container/k8s/engine.py
container/openshift/config.py
container/templates/init/container.j2.yml
container/utils/__init__.py
docs/rst/container_yml/reference.rst
test/roles/validate-build-and-import/tasks/main.yml
test/tests/validate_build.py
test/tests/validate_config.py

- Testing deploy with `ansible/django-gulp-nginx`, and fixing bugs and updating docs as a result.
- Fixes #533 
- Fixes #544 
- Fixes #540
- Fixes #541

Deploy bug fixes and clean up

---

container/config.py

I ran into this error on latest develop by having the following in my `container.yml`:
```
services:
foreman-base:
from: centos:7
roles:
- epel-repositories
- role: puppet-repositories
puppet_repositories_version: 4
- foreman-repositories
- katello-repositories
- foreman
openshift:
state: absent
```
```
ERROR	Unknown exception	
Traceback (most recent call last):
File "/home/ehelms/workspace/openshift/forklift/openshift/.tmp/ansible-container/container/cli.py", line 264, in __call__
getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
File "/home/ehelms/workspace/openshift/forklift/openshift/.tmp/ansible-container/container/__init__.py", line 28, in __wrapped__
return fn(*args, **kwargs)
File "/home/ehelms/workspace/openshift/forklift/openshift/.tmp/ansib …
```

Fix key error when specifying absent services

---

AUTHORS
container/config.py
container/docker/config.py
container/k8s/base_config.py
container/openshift/config.py
container/templates/init/container.j2.yml

Replaces #533
- Preserves @abstractproperty while fixing `TypeError: 'abstractproperty' object is not callable`
- Clean up of the `container.yml` template used by `init`
- Fixes bug regarding modification of dict that's being iterated in base config.set_env()

Fixes images_namespace property

---

AUTHORS
container/docker/engine.py
container/utils/__init__.py

Preseeds named and unnamed volumes on commit for instantiation. Thanks to @vbatts for his help.
```
version: "2"
settings:
conductor_base: centos:7
project_name: test555
services:
testsvc:
from: centos:7
roles:
- uncletouchy
volumes:
- ${HOME}:/me
- namedvol:/vol1
- /vol2
volumes:
namedvol:
docker: {}
registries: {}
- command: mkdir -p /vol1 /vol2
- command: touch /vol1/foo.txt /vol2/bar.txt
$ docker run -it --rm=true f35024476e5b67357bf73229739aae2db0ecf77154a48a833783c037697a8e80 bash
[root@31ad71768308 /]# ls /vol1
foo.txt
[root@31ad71768308 /]# ls /vol2
bar.txt
[root@31ad71768308 /]# mount
overlay on / type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/WHVVTREQCYXXVC63ZYG76XQRKZ:/var/lib/docker/overlay2/l/QCJM46P6OKLKG4S4UBW7MW5YYR:/var/lib/docker/overl …
```

Correctly pre-seed volumes during build. Fixes #555.

---

container/core.py

Before, if a `project_name` was not specified on the command line, the project name in a newly initialized `container.yml` would be `None`. With this fix, it's the directory name from the project path.

Fix default project name on init.

---

container/cli.py

Restore the definition of the --services option for builds accidently removed in 9ea1622

restores the --services option for builds

---

AUTHORS
conductor-requirements.txt
container/k8s/base_engine.py

Fixes #539 
Removed some leftover code in the `generate_orchestraion_playbook` method of k8s/base_engine.py that was attempting to interact with the `openshift` or `kubernetes` module, and update the authorization settings. Since we're not performing a real-time deployment, there's no point to interacting with the module at all.
During the `run` command it does make sense to pass along `settings.k8s_auth` from `container.yml`. Updated the Ansible Helper within the `openshift` module to look for `K8S_AUTH_` environment variables, and modified the `run_conductor` method to set these variables within the conductor. Now when `ansible-playbook` executes, modules will connect to the API using the expected settings.

Pass k8s_auth into conductor as ENV vars

---

container/docker/templates/conductor-dockerfile.j2

The six module is not a dependency of setuptools==36.0.0 that is why
we need to explicitly install it to eliminate `ImportError: No module named six`
messages.
Fixes #569
It is a temporary fix until setuptools is corrected.

Fix "ImportError: No module named six"

---

container/core.py
container/docker/engine.py
container/engine.py
docs/rst/container_yml/reference.rst

Closes #550 
Allows overriding the repository name prefix. Today we push images to a repository consisting of <project_name>-<service_name>. This change provides a mechanism for overriding the <project_name> portion of the repository name.

Adds repository_prefix registry attribute

---

AUTHORS
container/core.py
container/k8s/base_deploy.py
container/k8s/base_engine.py
container/openshift/deploy.py
docs/rst/reference/deploy.rst
docs/rst/reference/options/index.rst
docs/rst/reference/push.rst

Closes #565 
- Adds missing `create` tasks to the deployment playbook
- Adds `repository_prefix` registry attribute to k8s/openshift playbook generation
- Updates `deploy` and `push` docs

Fixes missing object creation tasks

---

container/cli.py
container/core.py
docs/rst/reference/build.rst

Two new options (--no-conductor-cache and --no-container-cache) are
added to allow fine grained caching control. The old --no-cache will
be kept and be an "alias" for which sets both new options.
Fixes #482

Split --no-cache into two options

---

AUTHORS
container/core.py
container/k8s/base_engine.py
docs/rst/container_yml/reference.rst

We push images into `minishift` using `https://local.openshift` as the registry URL. This is because the default IP address of `172.30.1.1` is not available outside of the VM, and so we create a `route` object, and associate it to an `/etc/hosts` entry. 
The flip side is also true, in that the host entry is not accessible inside the VM. Within the VM, the cluster expects to pull images via the `172.30.1.1` address. To accommodate this, I added a `pull_from_url` attribute to the registry properties. A registry definition within `container.yml` may now looking like the following:
```
...
registries:
openshift:
url: https://local.opeshift
namespace: demo
registry_prefix: foo
pull_from_url: https://172.30.1.1:5000
```
This PR also adds the tag value to the `image` …

Adds pull_from_url to registry

---

container/cli.py
container/core.py
container/docker/engine.py
container/engine.py
docs/rst/reference/build.rst
docs/rst/reference/deploy.rst
docs/rst/reference/destroy.rst
docs/rst/reference/push.rst
docs/rst/reference/restart.rst
docs/rst/reference/run.rst
docs/rst/reference/stop.rst

- `stop`, `run`, `restart`, and `destroy` should all run with the same `container.yml` configuration. In other words, if running locally, then all should use the `dev_overrides` options.
- Adds the `--production` option to `stop`, `run`, and `destroy`
- Split `ansible_args` for the engine into `ansible_build_args` and `ansible_orchestrate_args`. Prior to this all playbook runs happened with `-c docker`. However, when running against `localhost`, the options should be `-c local`. Thought this might fix the sporadically missing `--debug` output from playbook runs, but unfortunately it didn't. Still seems like a good idea though. 
- The docker_service module was updated. This PR will be the first to run with the latest changes.

Fix the stop command

---

container/k8s/base_engine.py

k8s_base engine was returning the wrong image ID for a given service. This PR fixes the problem.

Fix image tags

---

container/core.py

- Adds `--var-file` support to the `stop` and `restart` commands
- Closes #586

Adds --var-file support to stop and restart

---

AUTHORS
container/core.py

Passes variables defined in `settings.defaults` in `container.yml` and via `--var-file` to any roles executed during `build`. Adds the variables to the `vars` directive on the generated play.
Fixes #589

Pass config variablespace to build playbooks

---

container/config.py

Removes use of `basestring`, which is not Python3'able

Don't use 'basestring'

---

container/docker/templates/conductor-dockerfile.j2

The pull request in #603 didn't contain the addition of curl for rhel base images, so I'm adding that here. See my follow-up comments in #592.

Issue #592 fix missing curl package for rhel conductor setup.

---

container/core.py

Defines `ANSIBLE_CONTAINER` in the target (or service) container during `build`.
Closes #596

Adds ANSIBLE_CONTAINER=1 to target env

---

docs/rst/roles/access.rst

Insert a missing newline to enable proper rendering of the yaml codeblock.
A yaml code block is not rendering correctly
Insert a newline in order to fix the rendering.
```
```

Fix yaml code block rendering

---

AUTHORS
container/core.py
container/docker/engine.py
container/engine.py

Fixes #400 
During the build process, attempt to pull missing images. Images will be pulled from the engine's default registry. If using the default engine, Docker, then images will be pulled from Docker Hub. If this is not desired, then at this point, it's incumbent on the user to pull the images manually prior to running the build process. 
It may be possible, although not tested, for a registry to be included in the `from` directive, and if credentials exist in the default registry auth file (e.g. ~/.docker/config.json), for the images to be pulled from a private registry. This PR does mount the default auth file to the conductor, making it available to the `pull` process.

Pull missing images during build

---

container/k8s/base_engine.py
docs/rst/openshift/minishift.rst

- PR #646 broke the generated image path when running `deploy` with the K8s/OpenShift engines.
- Adds a note to the Minishift doc regarding how to access the registry

Fix k8s image path

---

container/cli.py
container/config.py
container/core.py
container/utils/__init__.py
docs/rst/container_yml/reference.rst
docs/rst/reference/options/index.rst
test/tests/validate_config.py

- Adds `--vars-files` CLI option, with `--var-file` and `--vars-file` as aliases, to accept one or more variables files as parameters.
- Adds `vars_files` option to settings
- Adds doc updates for `--vars-files` and `settings.vars_files`

Adds var_file to settings in container.yml

---

container/docker/engine.py
container/k8s/engine.py
container/openshift/engine.py

The pip syntax for extra_requires is
`pip install foo[bar]==0.0.1`, not `pip install foo==0.0.1[bar]`
```
$ pip install ansible-container==0.9.1[docker]
Collecting ansible-container==0.9.1[docker]
Could not find a version that satisfies the requirement
ansible-container==0.9.1[docker] (from versions: 0.1.0, 0.2.0, 0.3.0,
0.9.0.0, 0.9.1)
No matching distribution found for ansible-container==0.9.1[docker]
```
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

Fix pip install commands with extra_requires

---

container/config.py
container/docker/engine.py

Fixes missing build files when using --project-path

---

container/core.py

Volumes defined in container.yaml should be available also during container build phase. I belive this was intended by the authors, since in 668-678 of container/core.py there is loop over those volumes and it works if someone decides to use container's local python.

get volumes defined, mounted at container build time

---

container/docker/engine.py

It looks like issue #147 was originally resolved by PR #318, but I'm building a 1.8GB image in ansible-container 0.9.1 and getting the same behavior as that user originally reported - but neither exporting COMPOSE_HTTP_TIMEOUT=3000 to my outer "build" environment nor adding it to the conductor settings environment changes the (read timeout=60) in my error output.
If I add the timeout parameter to the Docker client instantiation in `container/docker/engine.py` as in the original pull request I am able to build the image.
The reason for the regression seems to be a switch from directly instantiating `docker.AutoVersionClient` to calling `docker.from_env`. It's not clear to me why `COMPOSE_HTTP_TIMEOUT` is not being used by `docker-py` internally when instantiating a …

Fixes #147 COMPOSE_HTTP_TIMEOUT regression

---

AUTHORS
container/config.py

Testing for a required key fails when the key exists but returns a falsy value. This fix makes it so the test only fails when the key is actually missing.

Only break when key is not present

---

AUTHORS
container/docker/engine.py

In `settings.volumes` expand variables like `${PWD}`

Allow for ${PWD} in settings.volumes

---

container/docker/engine.py

When pulling an image from a private registry this error occurs:
```python
Traceback (most recent call last):
--
File "/usr/bin/conductor", line 11, in <module>
load_entry_point('ansible-container', 'console_scripts', 'conductor')()
File "/_ansible/container/__init__.py", line 19, in __wrapped__
return fn(*args, **kwargs)
File "/_ansible/container/cli.py", line 392, in conductor_commandline
**params)
File "/_ansible/container/__init__.py", line 19, in __wrapped__
return fn(*args, **kwargs)
File "/_ansible/container/core.py", line 659, in conductorcmd_build
cur_image_id = engine.pull_image_by_tag(service['from'])
File "/_ansible/container/__init__.py", line 19, in __wrapped__
return fn(*args, **kwargs)
File "/_ansible/container/docker/engine.py", line 560, in …
```

Update split in docker pull

---

container/docker/engine.py

The variable `repository_prefix` has a `self` in front of it, but the variable is local scope rather than bound to the Engine class
`ansible-container deploy --push-to my-registry`
```
Traceback (most recent call last):
File "/usr/local/bin/conductor", line 11, in <module>
load_entry_point('ansible-container', 'console_scripts', 'conductor')()
File "/_ansible/container/__init__.py", line 19, in __wrapped__
return fn(*args, **kwargs)
File "/_ansible/container/cli.py", line 392, in conductor_commandline
**params)
File "/_ansible/container/__init__.py", line 19, in __wrapped__
return fn(*args, **kwargs)
File "/_ansible/container/core.py", line 923, in conductorcmd_push
password=password, repository_prefix=repository_prefix)
File "/_ansible/container/__init__.py", line …
```

Remove broken "self" before Docker engine's "repository_prefix" reference

---

AUTHORS
container/core.py
container/docker/templates/conductor-dockerfile.j2
container/utils/__init__.py
test/roles/validate-build-and-import/defaults/main.yml
test/roles/validate-build-and-import/files/trusty/ports.conf
test/roles/validate-build-and-import/templates/Dockerfile.j2
test/roles/validate-start-stop-restart/tasks/main.yml

Fixes #671 
Add to the hash any variables passed to the role on the `container.yml` line used to invoke it.
With this fix, `ansible-container --debug build` yields the following playbook output:
```
ok: [mongo]
META: ran handlers
TASK [setup_role : Show which_container] ***************************************
task path: /src/roles/setup_role/tasks/main.yml:1
ok: [mongo] => {
"which_container": "mongo"
}
TASK [setup_role : Show current host] ******************************************
task path: /src/roles/setup_role/tasks/main.yml:4
ok: [mongo] => {
"inventory_hostname": "mongo"
}
META: ran handlers
META: ran handlers
PLAY RECAP *********************************************************************
mongo                      : ok=3    changed=0    unreachable=0 …
```

Build cache fix

---

container/docker/templates/conductor-dockerfile.j2

Install the "sudo" package on the Conductor image for Debian and Ubuntu operating systems.
Fixes #575

Install the sudo package on Debian based operating systems

---

requirements.txt

For a source code installation of Ansible-Container to work on older operating systems (specially for the "match_markers" function), at least version 6.0 of Pip is required.
Fixes #543

Require Pip >= 6.0 for the match_markers method (#543)

---

AUTHORS
container/core.py
container/docker/engine.py
container/docker/templates/conductor-dockerfile.j2
container/engine.py

- New feature
Closes #566
Adds conductor environment variables defined in `container.yml` to the conductor image. Given the following in `container.yml`:
```
version: "2"
settings:
conductor:
base: centos:7
environment:
http_proxy: http://my.proxy.server:8000
https_proxy: https://my.proxy.server:84300
project_name: tstenv
```
The following ENV statements get added to the build Dockerfile:
```
Step 1/14 : FROM centos:7
---> 328edcd84f1b
Step 2/14 : ENV ANSIBLE_CONTAINER 1
---> Using cache
---> 2066daf83ee0
Step 3/14 : ENV http_proxy http://my.proxy.server:8000
---> Running in 9a36c1421e69
---> 892f46c876ef
Removing intermediate container 9a36c1421e69
Step 4/14 : ENV https_proxy https://my.proxy.server:84300
---> Running in 707d5fa56a08
---> 249df1272120
```

Add conductor environment during build

---

container/docker/engine.py
container/docker/secrets.py

Make Docker mount secrets in a manor consistent with Kubernetes.
Given the following in `container.yml`:
```
...
services:
web:
....
secrets:
postgres:
docker:
- postgres_user
- postgres_password
k8s:
- mount_path: '/run/secrets'
read_only: true
secrets:
cloudsql:
instance_credentials: cloudsql_key
postgres:
user: postgres_user
password: postgres_password
```
The following is generated in the `run` playbook:
```
tasks:
- shell: mkdir -p /run/secrets/postgres && echo '{{ postgres_password }}' >/run/secrets/postgres/password
name: Write secret to Docker volume
tags:
- start
- restart
- stop
- shell: mkdir -p /run/secrets/postgres && echo '{{ postgres_user }}' >/run/secrets/postgres/user
name: Write secret to Docker volume
tags:
- start
- restart
- stop
- shell: mkdir …
```

Mount secrets consistent with Kubernetes

---

proposals/multiple-containers.md

- Proposal Pull Request
Proposal that allows for multiple containers per pod to build services in container.yml that can use container patterns such as sidecars and ambassador. Currently a [TODO in the code](https://github.com/ansible/ansible-container/blob/0d54b0efba8a6bc205c0619226397201381e8e20/container/k8s/base_deploy.py#L358)

Add proposal for Multiple Containers per Pod

---

container/cli.py
container/docker/engine.py
container/k8s/base_engine.py
docs/rst/reference/build.rst

I'm attempting to setup Docker-out-of-Docker (i.e. mounting `/var/run/docker.sock`) in my Dockerized Jenkins CI environment, and found that (because Docker volume mounts via the socket always refer to host paths) I could not get the working directory (which is inside a Docker container) to mount into the sibling conductor container as `/src`.
To solve this, I need to mount `/src` with the path to my Jenkins `$JENKINS_HOME/workspace` on the **host** rather than the path to the workspace on the Jenkins build container.
This pull request adds an optional CLI flag to the `build` step, which overrides `base_path` in `engine.py` when mounting `/src` with the provided path
If the flag is not provided, `base_path` is mounted as usual.
I also added a flag to support the same …

Add CLI options to specify /src mount path and volume driver

---

AUTHORS
requirements.txt
setup.py

A bug in the Python library "docker" before 2.4.0 prevented images from correctly being used as `docker` would always look for the name "a"
Fixes #564

Require the Docker >= 2.4.0 Python library (#564)

---

container/docker/engine.py
container/docker/templates/conductor-local-dockerfile.j2
container/docker/templates/conductor-src-dockerfile.j2

- Feature pull request
The prebaked Conductors are... hefty. We're doing some things inefficiently. This PR reduces the images' sizes substantially.
e.g. Centos 7 prebake slims down from 595MB to 439MB.

Reduce Conductor base image sizes by like 25%.
